### ISSUE TITLE
Link to other github

### ISSUE THREAD

**Issue by Juris3D** [donnersm/TwinVisualizer#2]
Hello. Looks like DIYLAB-DE resource does not exist (deleted?)

**Comment by fbriceno97** [comment]
I am also looking for that documentation and it is gone. Wayback machine is not providing a lot of information from its archives https://web.archive.org/web/20220622215750/https://github.com/DIYLAB-DE/AudioVisualizer

**Comment by donnersm** [comment]
Sure,
I forked it here:
https://github.com/donnersm/AudioVisualizer
